version: "3.9"

services:
  bot:
    build: .
    environment:
      API_TOKEN: ${API_TOKEN}
      ADMIN_ID: ${ADMIN_ID}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: 5432
      WEBHOOK_HOST: ${WEBHOOK_HOST}
    ports:
      - "${PORT:-8080}:8080"
    volumes:
      - .:/app
