version: "3.9"

services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"

  bot:
    build: .
    depends_on:
      - db
    environment:
      API_TOKEN: ${API_TOKEN}
      ADMIN_ID: ${ADMIN_ID}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_HOST: dpg-d1uijhk9c44c73d1obbg-a
      WEBHOOK_HOST: ${WEBHOOK_HOST}
      DB_PORT: 5432
    ports:
      - "${PORT:-8080}:8080"  
    volumes:
      - .:/app

volumes:
  pgdata:
