services:
  - type: web
    name: tg-bot
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: false
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tg-bot-db
          property: connectionString
    port: 10000  # <- добавь эту строку
